name: Destroy Lambda

on:
  workflow_dispatch:   # Dispara manualmente

env:
  AWS_REGION: us-east-1
  TF_WORKSPACE: default

jobs:
  destroy-lambda:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      # 1️⃣ Checkout do repositório
      - uses: actions/checkout@v3

      # 2️⃣ Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # 5️⃣ Terraform Destroy apenas da Lambda
      - name: Terraform Destroy Lambda
        run: terraform destroy -target=aws_lambda_function.id_lambda -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_db_url: ${{ secrets.DB_URL }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_lambda_jar_path: app/target/lambda-identification-auth.jar
